apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: mq-hackathon
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
    - job_name: 'bcl-gateway'
      static_configs:
      - targets: ['bcl-gateway-svc:8000']
      metrics_path: /metrics

    - job_name: 'mq-fleet'
      static_configs:
      - targets: ['qm-src-a-svc:9443', 'qm-src-b-svc:9443']
      scheme: https
      tls_config:
        insecure_skip_verify: true
      metrics_path: /ibmmq/rest/v2/admin/qmgr

    - job_name: 'redis'
      static_configs:
      - targets: ['redis-svc:6379']

    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
